// Code generated by hertz generator.

package payment

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _payment0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paymentresultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paymentwaitingMw() []app.HandlerFunc {
	// your code...
	return nil
}
