// Code generated by Kitex v0.9.1. DO NOT EDIT.

package aiservice

import (
	"context"
	"errors"
	ai "github.com/SGNYYYY/gomall/rpc_gen/kitex_gen/ai"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Tool": kitex.NewMethodInfo(
		toolHandler,
		newToolArgs,
		newToolResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	aiServiceServiceInfo                = NewServiceInfo()
	aiServiceServiceInfoForClient       = NewServiceInfoForClient()
	aiServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aiServiceServiceInfo
}

// for client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aiServiceServiceInfoForStreamClient
}

// for stream client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aiServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AiService"
	handlerType := (*ai.AiService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "ai",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.9.1",
		Extra:           extra,
	}
	return svcInfo
}

func toolHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(ai.ToolReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(ai.AiService).Tool(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *ToolArgs:
		success, err := handler.(ai.AiService).Tool(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*ToolResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newToolArgs() interface{} {
	return &ToolArgs{}
}

func newToolResult() interface{} {
	return &ToolResult{}
}

type ToolArgs struct {
	Req *ai.ToolReq
}

func (p *ToolArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(ai.ToolReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *ToolArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *ToolArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *ToolArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *ToolArgs) Unmarshal(in []byte) error {
	msg := new(ai.ToolReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var ToolArgs_Req_DEFAULT *ai.ToolReq

func (p *ToolArgs) GetReq() *ai.ToolReq {
	if !p.IsSetReq() {
		return ToolArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *ToolArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ToolArgs) GetFirstArgument() interface{} {
	return p.Req
}

type ToolResult struct {
	Success *ai.ToolResp
}

var ToolResult_Success_DEFAULT *ai.ToolResp

func (p *ToolResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(ai.ToolResp)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *ToolResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *ToolResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *ToolResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *ToolResult) Unmarshal(in []byte) error {
	msg := new(ai.ToolResp)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *ToolResult) GetSuccess() *ai.ToolResp {
	if !p.IsSetSuccess() {
		return ToolResult_Success_DEFAULT
	}
	return p.Success
}

func (p *ToolResult) SetSuccess(x interface{}) {
	p.Success = x.(*ai.ToolResp)
}

func (p *ToolResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ToolResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Tool(ctx context.Context, Req *ai.ToolReq) (r *ai.ToolResp, err error) {
	var _args ToolArgs
	_args.Req = Req
	var _result ToolResult
	if err = p.c.Call(ctx, "Tool", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
